export const ListPeerChannelsSQL = "SELECT n.alias as node_alias, pc.peer_id, pc.channel_id, pc.short_channel_id, pc.state, pc.peer_connected, pc.to_us_msat, pc.total_msat, pc.their_to_self_delay, pc.opener, pc.private, pc.dust_limit_msat, pc.spendable_msat, pc.receivable_msat, pc.funding_txid FROM peerchannels pc LEFT JOIN nodes n ON pc.peer_id = n.nodeid;";

export const ListOffersSQL = (limit, offset) => "SELECT offer_id, active, single_use, bolt12, used, label, COALESCE(description, NULL) as description FROM offers ORDER BY offer_id LIMIT " + limit + " OFFSET " + offset;

// We use a single-query approach instead of splitting these queries because it:
// - Keeps the code simpler and easier to reason about
// - Reduces the risk of bugs
// - Is easier to maintain over time
// - Performs better for the common case (~20K-40K total records; typically 1–5 pages fetched)
// - Break even at ~8-9 pages with a page size of 100
export const listLightningTransactionsSQL = (limit, offset) => "WITH unique_payment_hashes AS (SELECT payment_hash, created_at as sort_time FROM (SELECT DISTINCT payment_hash, MAX(created_at) as created_at FROM sendpays GROUP BY payment_hash)), unique_invoice_hashes AS (SELECT payment_hash, COALESCE(paid_at, expires_at) as sort_time FROM invoices WHERE status != 'expired'), all_unique_hashes AS (SELECT payment_hash, sort_time FROM unique_payment_hashes UNION ALL SELECT payment_hash, sort_time FROM unique_invoice_hashes), paginated_hashes AS (SELECT DISTINCT payment_hash FROM all_unique_hashes ORDER BY sort_time DESC LIMIT " + limit + " OFFSET " + offset + ") SELECT 'INVOICE' as type, i.payment_hash, i.status, i.label, i.description, i.bolt11, i.bolt12, i.payment_preimage, i.amount_msat, i.amount_received_msat, i.expires_at, i.paid_at, NULL as completed_at, NULL as groupid, NULL as partid, COALESCE(i.paid_at, i.expires_at) as sort_time FROM invoices i INNER JOIN paginated_hashes ph ON i.payment_hash = ph.payment_hash WHERE i.status != 'expired' UNION ALL SELECT 'PAYMENT' as type, s.payment_hash, s.status, s.label, s.description, s.bolt11, s.bolt12, s.payment_preimage, s.amount_msat, s.amount_sent_msat, s.created_at, s.completed_at, s.destination, s.groupid, s.partid, s.created_at as sort_time FROM sendpays s INNER JOIN paginated_hashes ph ON s.payment_hash = ph.payment_hash ORDER BY sort_time DESC;";

export const listBTCTransactionsSQL = (limit, offset) => "WITH unique_timestamps AS (SELECT DISTINCT timestamp FROM bkpr_accountevents WHERE account = 'wallet' AND (tag = 'deposit' OR tag = 'withdrawal') ORDER BY timestamp DESC LIMIT " + limit + " OFFSET " + offset + ") SELECT e.blockheight, e.credit_msat, e.debit_msat, e.outpoint, e.tag, e.timestamp, e.txid FROM bkpr_accountevents e INNER JOIN unique_timestamps ut ON e.timestamp = ut.timestamp WHERE e.account = 'wallet' AND (e.tag = 'deposit' OR e.tag = 'withdrawal') ORDER BY e.timestamp DESC;";

