name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Get version from package.json
      id: package-version
      run: |
        echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        echo "Project Version: $VERSION"

    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-npm-packages
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

    - name: Install NPM dependencies
      if: steps.cache-npm-packages.outputs.cache-hit != 'true'
      run: npm clean-install

    - name: Check lint errors
      run: npm run lint
